openstack-charmers/openstack-bundles

- stable/openstack-base/README.md
- stable/openstack-lxd/README.md
Starting with Newton, if the user doesn't complete this step first, the next
step (booting an instance) will fail. Fixes #11.
> Add a step under "Ensuring it's working" for creating an initial flavor

- development/openstack-base-spaces/bundle.yaml
- development/openstack-base-trusty-mitaka/bundle.yaml
- development/openstack-base-xenial-mitaka/bundle.yaml
- development/openstack-dpdk/bundle.yaml
- development/openstack-lxd/bundle.yaml
- stable/openstack-base/bundle.yaml
- stable/openstack-lxd/bundle.yaml
- stable/openstack-telemetry/bundle.yaml
Remove the arch constraint blocking deployment on arm64, and update nova-compute charm to a version that supports EFI VMs by default on arm64.
> Support arm64

- development/openstack-base-xenial-ocata/bundle.yaml
This is required for OpenStack Ocata and beyond to support Boot From
Volume.
References:
0: https://github.com/openstack/nova/commit/b89efa3ef611a1932df0c2d6e6f30315b5111a57
1: https://bugs.launchpad.net/bugs/1671422
Fixes #31
> Add ceph-access relation between nova-compute and cinder-ceph

- development/openstack-base-spaces/README.md
- development/openstack-base-xenial-mitaka/README.md
- development/openstack-base-xenial-newton/README.md
- development/openstack-base-xenial-ocata/README.md
- development/openstack-base-xenial-pike/README.md
- stable/openstack-base/README.md
arm64 cloud images must have the "hw_firmware_type" property set to uefi.
There is no legacy BIOS option for ARM. This is also true for armhf images,
but I don't believe those images *just work* in UEFI mode yet, and I don't
want to imply otherwise until they do.
> Add instructions for importing arm64 cloud images

- development/ceph-base-bionic-luminous/bundle.yaml
- development/ceph-base-xenial-jewel/bundle.yaml
- development/ceph-base-xenial-luminous/bundle.yaml
- development/openstack-base-bionic-queens/bundle.yaml
- development/openstack-base-spaces/bundle.yaml
- development/openstack-base-xenial-mitaka/bundle.yaml
- development/openstack-base-xenial-newton/bundle.yaml
- development/openstack-base-xenial-ocata/bundle.yaml
- development/openstack-base-xenial-pike/bundle.yaml
- development/openstack-base-xenial-queens/bundle.yaml
- development/openstack-lxd-xenial-mitaka/bundle.yaml
Resolve error on more recent series, where the official charm contains series support, and the old tactical fork does not.
ERROR cannot post archive: bundle verification failed: ["application \"ntp\" refers to non-existent charm \"cs:~openstack-charmers-next/bionic/ntp\""]
> Use the official ntp charm instead of an old fork

- development/openstack-lxd-xenial-queens/README.md
- development/openstack-lxd-xenial-queens/bundle.yaml
- development/openstack-lxd-xenial-queens/neutron-ext-net-ksv3
- development/openstack-lxd-xenial-queens/neutron-tenant-net-ksv3
- development/openstack-lxd-xenial-queens/novarc_auto
This patchset adds a xenial-queens bundle to create a cloud that
uses LXD as the hypervisor.  Includes updated README files for
using the openstack client rather than the individual project
clients.  Also, updates the queens tools links to use the
keystone v3 versions as queens keystone is v3 only.
> Add xenial-queens bundle for LXD and fix xenial-mitaka bundle

- stable/openstack-telemetry/bundle.yaml
Updated stable/telemetry bundle
-- gnocchi charm to include cloud-archive, tested on bare metal.
> Updated ghnocchi charm to include cloud-archive in stable-telemetry

- development/openstack-base-bionic-queens/bundle.yaml
- development/openstack-telemetry-bionic-queens/bundle.yaml
This makes the bionic-queens bundles match the xenial-queens
bundles, with the exception of openstack-origin and source
charm config options, which should be default (distro) in
the case of bionic-queens.
> Update bionic-queens bundles

- development/shared/openrc
Use `project` scoped token by default
Add OS_AUTH_TYPE variable needed by Gnocchi client
> Openrc fixup

- development/overlays/encryption-at-rest.yaml
- stable/overlays/encryption-at-rest.yaml
Add devel and stable overlays for upcoming encryption at rest
feature using vault.
This include coverage for ceph-osd and nova-compute; swift is
no included in the openstack-base bundle so is skipped for now.
> Add overlays for encryption at rest

- development/ceph-base-bionic-luminous/bundle.yaml
- development/ceph-base-xenial-jewel/bundle.yaml
- development/ceph-base-xenial-luminous/bundle.yaml
- development/openstack-base-bionic-queens/bundle.yaml
- development/openstack-base-spaces/bundle.yaml
- development/openstack-base-xenial-mitaka/bundle.yaml
- development/openstack-base-xenial-newton/bundle.yaml
- development/openstack-base-xenial-ocata/bundle.yaml
- development/openstack-base-xenial-pike/bundle.yaml
- development/openstack-base-xenial-queens/bundle.yaml
- development/openstack-dpdk/bundle.yaml
- development/openstack-lxd-bionic-queens/bundle.yaml
- development/openstack-lxd-xenial-mitaka/bundle.yaml
- development/openstack-lxd-xenial-queens/bundle.yaml
- development/openstack-refstack-xenial-ocata-ppc64el-alt/bundle.yaml
- development/openstack-refstack-xenial-ocata/bundle.yaml
- development/openstack-refstack-xenial-pike-ppc64el-alt/bundle.yaml
- development/openstack-refstack-xenial-pike/bundle.yaml
- development/openstack-telemetry-bionic-queens/bundle.yaml
- development/openstack-telemetry-xenial-mitaka/bundle.yaml
- development/openstack-telemetry-xenial-newton/bundle.yaml
- development/openstack-telemetry-xenial-ocata/bundle.yaml
- development/openstack-telemetry-xenial-pike/bundle.yaml
- development/openstack-telemetry-xenial-queens/bundle.yaml
- stable/ceph-base/bundle.yaml
- stable/openstack-base/bundle.yaml
- stable/openstack-lxd/bundle.yaml
- stable/openstack-telemetry/bundle.yaml
While these configuration options may give a smooth deploy
and test experience, they do not come without peril when
used in the wrong situation or left on in deployment that
matures into production.
> Remove `osd-reformat` and `overwrite` options from bundles

- development/push-and-publish.sh
- stable/push-and-publish.sh
Both for stable and development bundles.
Although the development bundles are in the `openstack-charmers-next`
namespace and not promulgated to the first page, we do have community
users taking them for a spin.  They should know where to find us.
> Add bugs-url and homepage links when publishing bundles

- development/ceph-base-bionic-luminous/bundle.yaml
- development/openstack-base-xenial-queens/bundle.yaml
- development/openstack-lxd-xenial-queens/bundle.yaml
- development/openstack-telemetry-xenial-queens/bundle.yaml
Bionic main and xenial-queens UCA have the necessary bits.
Developing towards the proposed archives may lead to
inconsistent results as bits there may change or indeed
disappear before they hit main archives.
> Remove proposed as source/origin for development bundles

- development/openstack-lxd-xenial-mitaka/README.md
Just a small typo -- mising some `$` signs in the bash scripts which meant they wouldn't work.
> Fix README typo for lxd xenial mitaka bundle

- development/overlays/loadbalancer-octavia.yaml
- stable/overlays/loadbalancer-octavia.yaml
A late amendment to the relation type between Octavia
and Neutron OpenvSwitch did not make it into the bundles.
> Fix neutron-openvswitch relation in Octavia overlays

- development/openstack-lxd-xenial-mitaka/bundle.yaml
remove references to xenial-mitaka as there is no such cloud pocket with that name (mitaka is default for xenial)
> missed these mistake in the last commit

- stable/overlays/openstack-base-virt-overlay.yaml
Commit 5d301f8f3a0c8b3b0d70fa8ab02099ac27b68db4 introduced base
bundle.yaml bindings support, enabling deployment of applications
to the public-space space. This caused problems with the existing
openstack-base-virt-overlay.yaml so here we bring the virt overlay
up to speed by disabling bindings.
> Disable bindings in openstack base virt overlay

- stable/overlays/openstack-base-virt-overlay.yaml
I'm requesting that we give more memory to the compute nodes so we give the user a better experience when launching a few test instances. Without this change these nodes only get 1.5GiB.
> Apply memory constraint to nova-compute application

- development/openstack-telemetry-bionic-queens/bundle.yaml
- development/openstack-telemetry-bionic-rocky/bundle.yaml
- development/openstack-telemetry-bionic-stein/bundle.yaml
- development/openstack-telemetry-cosmic-rocky/bundle.yaml
- development/openstack-telemetry-disco-stein/bundle.yaml
- development/openstack-telemetry-xenial-mitaka/bundle.yaml
- development/openstack-telemetry-xenial-newton/bundle.yaml
- development/openstack-telemetry-xenial-ocata/bundle.yaml
- development/openstack-telemetry-xenial-pike/bundle.yaml
- development/openstack-telemetry-xenial-queens/bundle.yaml
- stable/ceph-base/bundle.yaml
- stable/openstack-lxd/bundle.yaml
- stable/openstack-telemetry/bundle.yaml
- stable/overlays/openstack-base-virt-overlay.yaml
The rabbitmq ceilometer-agent relation is described in the
19.04 charm release notes.
> 19.07 bundles and rabbitmq ceilometer-agent relations

- development/openstack-base-bionic-train/README.md
- development/overlays/openstack-base-ovn.yaml
- stable/openstack-base/README.md
- stable/overlays/openstack-base-ovn.yaml
A OVN based deployment only needs 3 machines.
Re-map placement targeted to the fourth machine.
> Add OVN overlay

- development/openstack-base-eoan-train-mysql8-ovn/bundle.yaml
- development/overlays/openstack-base-ovn.yaml
- stable/overlays/openstack-base-ovn.yaml
On the back of openstack-charmers/charm-layer-ovn#6 and LP: #1850956
we changed the OVN Chassis charms to align with previous networking
charms wrt. how interfaces are mapped to bridges.  Update overlays
to use the changed configuration option.
> Update OVN overlays bridge-interface-mappings

- development/shared/test-requirements.txt
- development/ubuntu-lite-series-upgrade-bionic/README.md
- development/ubuntu-lite-series-upgrade-bionic/bundle.yaml
- development/ubuntu-lite-series-upgrade-bionic/test-requirements.txt
- development/ubuntu-lite-series-upgrade-bionic/tests/bundles/bundle.yaml
- development/ubuntu-lite-series-upgrade-bionic/tests/tests.yaml
- development/ubuntu-lite-series-upgrade-bionic/tox.ini
- development/ubuntu-lite-series-upgrade-trusty/README.md
- development/ubuntu-lite-series-upgrade-trusty/bundle.yaml
- development/ubuntu-lite-series-upgrade-trusty/test-requirements.txt
- development/ubuntu-lite-series-upgrade-trusty/tests/bundles/bundle.yaml
- development/ubuntu-lite-series-upgrade-trusty/tests/tests.yaml
- development/ubuntu-lite-series-upgrade-trusty/tox.ini
- development/ubuntu-lite-series-upgrade-xenial/README.md
- development/ubuntu-lite-series-upgrade-xenial/bundle.yaml
- development/ubuntu-lite-series-upgrade-xenial/test-requirements.txt
- development/ubuntu-lite-series-upgrade-xenial/tests/bundles/bundle.yaml
- development/ubuntu-lite-series-upgrade-xenial/tests/tests.yaml
- development/ubuntu-lite-series-upgrade-xenial/tox.ini
An example of this running the xenial --> bionic upgrade
```bash
2020-04-15 16:11:52 [INFO] ok
2020-04-15 16:11:52 [INFO] ----------------------------------------------------------------------
2020-04-15 16:11:52 [INFO] Ran 1 test in 875.331s
2020-04-15 16:11:52 [INFO] OK
2020-04-15 16:11:52 [INFO] Events:
Deploy Bundle:
Start: 1586958982.2283154
Finish: 1586958992.1511385
Elapsed Time: 9.922823190689087
PCT Of Run Time: 2
Prepare Environment:
Start: 1586958964.061425
Finish: 1586958982.2274125
Elapsed Time: 18.165987491607666
PCT Of Run Time: 2
Test zaza.openstack.charm_tests.series_upgrade.parallel_tests.XenialBionicSeriesUpgradeUbuntu:
Start: 1586959036.9020543
Finish: 1586959912.5931423
Elapsed Time: 875.6910879611969
PCT Of Run Time: 93
Wait for Deployment:
Start: 1586958992.151174 …
```
> Add ubuntu-lite bundles that validate parallel series upgrade

- development/openstack-base-bionic-ussuri-ovn/README.md
- development/openstack-base-bionic-ussuri-ovn/neutron-ext-net-ksv3
- development/openstack-base-bionic-ussuri-ovn/neutron-tenant-net-ksv3
- development/openstack-base-bionic-ussuri/README.md
- development/openstack-base-bionic-ussuri/neutron-ext-net-ksv3
- development/openstack-base-bionic-ussuri/neutron-tenant-net-ksv3
- development/openstack-base-focal-ussuri-ovn/README.md
- development/openstack-base-focal-ussuri-ovn/neutron-ext-net-ksv3
- development/openstack-base-focal-ussuri-ovn/neutron-tenant-net-ksv3
- development/openstack-telemetry-bionic-ussuri/neutron-ext-net-ksv3
- development/openstack-telemetry-bionic-ussuri/neutron-tenant-net-ksv3
- development/openstack-telemetry-focal-ussuri-ovn/neutron-ext-net-ksv3
- development/openstack-telemetry-focal-ussuri-ovn/neutron-tenant-net-ksv3
- development/shared/neutron-ext-net-ksv3
- development/shared/neutron-tenant-net-ksv3
While the proprietary Python scripts are valuable for our internal
testing they do not provide much educational value for our end
users.
Replace use of the scripts with examples of how to do post deploy
configuration using the OpenStack CLI for ussuri bundles.
> Update post deploy network configuration instructions

- development/openstack-base-focal-ussuri-ovn/README.md
- stable/openstack-base/README.md
The README currently only references documentation on how to
unseal vault, we should also reference documentation on how to
set up the root CA.
Should be merged with https://review.opendev.org/#/c/735857/
> Update instructions on how to issue certs to deployment

- development/shared/openrcv2
- development/shared/openrcv3_domain
- development/shared/openrcv3_project
- stable/shared/openrcv2
- stable/shared/openrcv3_domain
- stable/shared/openrcv3_project
Just as every other OS_* setting is reset OS_AUTH_PROTOCOL and OS_CACERT
should also be reset.
Closes-Bug: #1883290
> Reset OS_AUTH_PROTOCOL and OS_CACERT

- development/overlays/loadbalancer-octavia.yaml
- development/overlays/masakari-bionic-ussuri.yaml
https://bugs.launchpad.net/openstack-bundles/+bug/1895662
> Warn user that bundle and overlay must have matching openstack-origin

- development/openstack-base-focal-ussuri-ovn/openrc
- development/openstack-base-focal-victoria/openrc
- development/openstack-base-focal-wallaby/openrc
- development/openstack-base-groovy-victoria/openrc
- development/openstack-telemetry-focal-ussuri-ovn/openrc
- development/openstack-telemetry-focal-victoria/openrc
- development/openstack-telemetry-focal-wallaby/openrc
- development/openstack-telemetry-groovy-victoria/openrc
I'm reverting here a mistake I did recently. Without this fix, you'll get an HTTP/400 from keystone when talking to the API. Validated on an arm64 lab.
> Fix openrc symlinks

- development/ceph-base-groovy-octopus/README.md
- development/ceph-base-groovy-octopus/bundle.yaml
- development/ceph-base-groovy-octopus/test-requirements.txt
- development/ceph-base-groovy-octopus/tests/bundles/bundle.yaml
- development/ceph-base-groovy-octopus/tests/bundles/overlays/bundle.yaml.j2
- development/ceph-base-groovy-octopus/tests/tests.yaml
- development/ceph-base-groovy-octopus/tox.ini
- development/ceph-base-groovy-octopus/validate-ceph.sh
This is just a copy of `ceph-base-focal-octopus` with `s/focal/groovy/`
> Add ceph-base-groovy-octopus bundle

- development/openstack-base-bionic-ussuri-ovn/openrc
- development/openstack-base-bionic-ussuri/openrc
This aligns the bionic-ussuri* bundles to newer bundles
like focal-ussuri-ovn.
Validated against an s390x lab.
> Fix symlinks

- development/ceph-base-hirsute-pacific/README.md
- development/ceph-base-hirsute-pacific/bundle.yaml
- development/ceph-base-hirsute-pacific/test-requirements.txt
- development/ceph-base-hirsute-pacific/tests/bundles/bundle.yaml
- development/ceph-base-hirsute-pacific/tests/bundles/overlays/bundle.yaml.j2
- development/ceph-base-hirsute-pacific/tests/tests.yaml
- development/ceph-base-hirsute-pacific/tox.ini
- development/ceph-base-hirsute-pacific/validate-ceph.sh
The only difference with ceph-base-groovy-octopus is
s/groovy/hirsute/
> Add ceph-base-hirsute-pacific bundle

- development/openstack-base-focal-wallaby/README.md
Full review and update of the README
A bundle is for deployment. Remove two sections
related to cloud operations:
* Adding Cinder volumes
* Scaling out of ceph-osd and nova-compute units
> Refresh dev openstack-base README

- development/openstack-base-focal-wallaby/README.md
The focal-wallaby openstack-base bundle README needed a correction in the Ceph version provided.
> Fix Ceph version in dev openstack-base README

- stable/openstack-base/README.md
This was missed during the last big bundle update (https://github.com/openstack-charmers/openstack-bundles/pull/212).
This proposed README was overhauled recently (https://github.com/openstack-charmers/openstack-bundles/pull/209) and is now in the dev focal-wallaby directory. Then I:
* removed the first line
* explicitly set openstack-origin to `cloud:focal-wallaby` in the variables section.
**Please push this change to the Charm Store.**
> Update stable openstack-base README

- development/openstack-base-bionic-stein/bundle.yaml
- development/openstack-base-bionic-train/bundle.yaml
- development/openstack-base-bionic-ussuri-ovn/bundle.yaml
- development/openstack-base-bionic-ussuri/bundle.yaml
- development/openstack-base-eoan-train-mysql8-migration/bundle.yaml
- development/openstack-base-eoan-train-mysql8-ovn/bundle.yaml
- development/openstack-base-eoan-train/bundle.yaml
- development/openstack-base-focal-ussuri-ovn/bundle.yaml
- development/openstack-base-focal-victoria/bundle.yaml
- development/openstack-base-focal-wallaby/bundle.yaml
- development/openstack-base-focal-xena/bundle.yaml
- development/openstack-base-groovy-victoria/bundle.yaml
- development/openstack-base-hirsute-wallaby/bundle.yaml
- development/openstack-base-impish-xena/bundle.yaml
- development/openstack-converged-networking-focal-ussuri/bundle.yaml
- development/openstack-ha/masakari-mosci.yaml
- development/openstack-telemetry-bionic-stein/bundle.yaml
- development/openstack-telemetry-bionic-train/bundle.yaml
- development/openstack-telemetry-bionic-ussuri/bundle.yaml
- development/openstack-telemetry-focal-ussuri-ovn/bundle.yaml
- development/openstack-telemetry-focal-victoria/bundle.yaml
- development/openstack-telemetry-focal-wallaby/bundle.yaml
- development/openstack-telemetry-focal-xena/bundle.yaml
- development/openstack-telemetry-groovy-victoria/bundle.yaml
- development/openstack-telemetry-impish-xena/bundle.yaml
- development/overlays/openstack-base-ovn.yaml
- stable/openstack-base/bundle.yaml
- stable/openstack-telemetry/bundle.yaml
- stable/overlays/openstack-base-ovn.yaml
Since the bridge mappings are environment-specific, they are commented
out so that users can set them on their own.
On a related note, we test these bundles with zaza-openstack-tests, which
will configure the bridge mappings only if the bridge mapping config is not
already set by the bundle or otherwise. [1]
[1] https://github.com/openstack-charmers/zaza-openstack-tests/pull/625
> Comment out bridge-interface-mappings as it is environment specific

- development/openstack-base-hirsute-wallaby/README.md
- development/openstack-base-impish-xena/README.md
- stable/openstack-base/README.md
Changes:
- Added \ at the end of multiline terminal commands for easier use
- fixed subnet-range to be a proper CIDR
> Openstack-base README typos fixes

- development/overlays/openstack-base-virt-overlay.yaml
It seems like the stable virt-overlay got improved
over time and the development one got forgotten
along the way.
> Align dev virt-overlay to stable one

- development/openstack-base-focal-yoga/bundle.yaml
Update the openstack-base bundle to focal-yoga.
The bundle has been verified.
Remove the `worker-multiplier` option for containerised services as this leads to too many processes on highly
resourced machines. There is already a default maximum number of four.
> Update openstack-base to focal-yoga

- development/overlays/openstack-base-virt-overlay.yaml
- stable/overlays/openstack-base-virt-overlay.yaml
juju >= 2.9.29 does not accept empty strings as network space names, so
we introduce a variable that defaults to the default network space name
of "alpha"
Closes-bug: #1971633
Signed-off-by: Mert Kırpıcı <mert.kirpici@canonical.com>
> overlays/os-base-virt: add variable default-space

- development/openstack-base-bionic-queens/bundle.yaml
- development/openstack-base-bionic-rocky/bundle.yaml
- development/openstack-base-bionic-stein/bundle.yaml
- development/openstack-base-bionic-train/bundle.yaml
- development/openstack-base-bionic-ussuri/bundle.yaml
- development/openstack-base-eoan-train-mysql8-migration/bundle.yaml
- development/openstack-base-eoan-train-mysql8-ovn/bundle.yaml
- development/openstack-base-eoan-train/bundle.yaml
- development/openstack-base-jammy-yoga/bundle.yaml
- development/openstack-base-spaces/bundle.yaml
- development/openstack-base-xenial-mitaka/bundle.yaml
- development/openstack-base-xenial-newton/bundle.yaml
- development/openstack-base-xenial-ocata/bundle.yaml
- development/openstack-base-xenial-pike/bundle.yaml
- development/openstack-base-xenial-queens/bundle.yaml
- development/openstack-ha/masakari-mosci.yaml
- development/openstack-refstack-xenial-ocata-ppc64el-alt/bundle.yaml
- development/openstack-refstack-xenial-pike-ppc64el-alt/bundle.yaml
- development/openstack-telemetry-bionic-train/bundle.yaml
- development/openstack-telemetry-bionic-ussuri/bundle.yaml
Previously, charm urls could reference Ubuntu series as part of the
charm that was being delivered (e.g. <team>/<series>/<charm>). Some
of the legacy bundles in this repository used this particular URL
schema to target specific series of charms.
However, this was deprecated as the series was added to the charm
metadata and the new charmhub store does not support this particular
API and subsequently causes the lint tests to fail as a result.
This removes all of these urls from the bundles in order to allow
the lint checks to pass.
Signed-off-by: Billy Olsen <billy.olsen@gmail.com>
> Drop legacy charm urls from bundles

- development/ceph-base-focal-quincy/README.md
- development/ceph-base-focal-quincy/bundle.yaml
- development/ceph-base-focal-quincy/charmcraft.yaml
- development/ceph-base-focal-quincy/test-requirements.txt
- development/ceph-base-focal-quincy/tests/bundles/bundle.yaml
- development/ceph-base-focal-quincy/tests/bundles/overlays/bundle.yaml.j2
- development/ceph-base-focal-quincy/tests/tests.yaml
- development/ceph-base-focal-quincy/tox.ini
- development/ceph-base-focal-quincy/validate-ceph.sh
- development/ceph-base-jammy-quincy/bundle.yaml
- development/ceph-base-jammy-quincy/charmcraft.yaml
- development/openstack-base-focal-yoga/bundle.yaml
- development/openstack-base-focal-yoga/charmcraft.yaml
- development/openstack-base-jammy-yoga/bundle.yaml
- development/openstack-base-jammy-yoga/charmcraft.yaml
- development/openstack-telemetry-focal-yoga/bundle.yaml
- development/openstack-telemetry-focal-yoga/charmcraft.yaml
- development/openstack-telemetry-jammy-yoga/bundle.yaml
- development/openstack-telemetry-jammy-yoga/charmcraft.yaml
- stable/ceph-base/README.md
- stable/ceph-base/bundle.yaml
- stable/ceph-base/charmcraft.yaml
- stable/openstack-base/README.md
- stable/openstack-base/bundle.yaml
- stable/openstack-base/charmcraft.yaml
- stable/openstack-telemetry/bundle.yaml
- stable/openstack-telemetry/charmcraft.yaml
- stable/push-and-publish.sh
Update the openstack-bundles repository to use charmcraft for bundle publishing and update the stable bundles to release focal-yoga and focal-quincy.
> Charmhub migration

- stable/openstack-telemetry/bundle.yaml
Make the following improvements to the stable `openstack-telemetry` bundle to be consistent with the stable `openstack-base` bundle:
- Use the `stable` risk level (instead of `edge`)
- Remove the deprecated `worker-multiplier` options
- Move the `channel:` lines underneath the `charm:` lines
We should endeavour to bring in the last two changes to the "source" bundles to avoid having to repeatedly make these changes.
> Improve stable openstack-telemetry bundle

- stable/openstack-telemetry/bundle.yaml
Update stable openstack-telemetry for focal-yoga to be more consistent with the stable openstack-base bundle:
* remove extraneous series lines
* remove charm CI variable `local_overlay_enabled`
* add a bundle name to make charmcraft happy
> Update stable openstack-telemetry for focal-yoga

- development/openstack-base-jammy-yoga/bundle.yaml
**Ideally do not merge until `22.04.1` is released (ETA: August 11).** 
Make the following improvements to the dev `openstack-base` jammy-yoga bundle:
- Use the `8.0` track for the MySQL charms (instead of `8.0.19`)
- Use the `stable` risk level (instead of `edge`)
- Remove the deprecated `worker-multiplier` options
- Move the `channel:` lines underneath the `charm:` lines
> Improve dev openstack-base bundle for jammy-yoga

- stable/openstack-base/bundle.yaml
a deployment is fine as of right now, but Juju is dropping cs: support.
Also, cs: makes `juju export-bundle --include-charm-defaults` fail.
> use NTP charm from charmhub
