- stable/openstack-base/bundle.yaml
- stable/openstack-lxd/bundle.yaml
- stable/openstack-telemetry/bundle.yaml
Stable bundles updated with 16.10 versions of the charms
> 16.10 Stable Release

- stable/openstack-base/README.md
- stable/openstack-base/bundle.yaml
- stable/openstack-lxd/README.md
- stable/openstack-lxd/bundle.yaml
- stable/openstack-telemetry/bundle.yaml
Update the stable bundles to deploy OpenStack Newton.
> Update stable bundles -> OpenStack Newton

- development/openstack-lxd/bundle.yaml
- stable/openstack-base/README.md
- stable/openstack-base/bundle.yaml
- stable/openstack-lxd/bundle.yaml
- stable/openstack-telemetry/bundle.yaml
- tools/update-bundle-versions
Update Stable Bundles for 17.02
> Update Stable Bundles for 17.02

- development/openstack-base-spaces/bundle.yaml
Update net spaces bundle with new bindings, relations and config options
> Update bindings in net space deploy

- development/ceph-base-bionic-luminous/README.md
- development/ceph-base-bionic-luminous/bundle.yaml
- development/ceph-base-bionic-luminous/validate-ceph.sh
should only need this, as it seems unlikely we will be deploying jewel on bionic.
> add ceph base bionic (queens, luminous)

- development/openstack-base-bionic-queens/README.md
- development/openstack-base-bionic-queens/bundle.yaml
- development/openstack-base-bionic-queens/neutron-ext-net
- development/openstack-base-bionic-queens/neutron-tenant-net
- development/openstack-base-bionic-queens/novarc
- development/openstack-base-xenial-queens/README.md
- development/openstack-base-xenial-queens/bundle.yaml
- development/openstack-base-xenial-queens/neutron-ext-net
- development/openstack-base-xenial-queens/neutron-tenant-net
- development/openstack-base-xenial-queens/novarc
- development/openstack-telemetry-bionic-queens/README.md
- development/openstack-telemetry-bionic-queens/bundle.yaml
- development/openstack-telemetry-bionic-queens/neutron-ext-net
- development/openstack-telemetry-bionic-queens/neutron-tenant-net
- development/openstack-telemetry-bionic-queens/novarc
- development/openstack-telemetry-xenial-queens/README.md
- development/openstack-telemetry-xenial-queens/bundle.yaml
- development/openstack-telemetry-xenial-queens/neutron-ext-net
- development/openstack-telemetry-xenial-queens/neutron-tenant-net
- development/openstack-telemetry-xenial-queens/novarc
added bionic and queens bundles for openstack-base and openstack-telemetry
unsure if auth_url in novarc should be using v2 or v3 URL - please comment before merging
> added bionic and queens bundles

- stable/ceph-base/bundle.yaml
- stable/openstack-base/bundle.yaml
- stable/openstack-lxd/bundle.yaml
- stable/openstack-telemetry/bundle.yaml
> Update charm revs for stable

- stable/ceph-base/bundle.yaml
- stable/openstack-base/bundle.yaml
- stable/openstack-lxd/bundle.yaml
- stable/openstack-telemetry/bundle.yaml
Among other things this includes the following backports:
- https://review.openstack.org/#/c/563854/
- https://review.openstack.org/#/c/562622/
> Update stable charm revs

- development/openstack-lxd-xenial-queens/README.md
> Change Mitka -> Queens in dev xenial-queens lxd README

- development/openstack-lxd-bionic-queens/README.md
- development/openstack-lxd-bionic-queens/bundle.yaml
- development/openstack-lxd-bionic-queens/neutron-ext-net-ksv3
- development/openstack-lxd-bionic-queens/neutron-tenant-net-ksv3
- development/openstack-lxd-bionic-queens/openrc
- development/shared/openrc
This is verified as working on the dev charms for bionic/queens.
The sources have been commented out in the bundle (not needed for
bionic), but left in as a reminder for when they are needed.
> [WIP] Add bionic-queens lxd bundle/instructions

- stable/openstack-lxd/README.md
- stable/openstack-lxd/bundle.yaml
This is the 2nd stab at getting the stable bionic changes for openstack lxd.
> Stable bionic openstack lxd (version 2)

- development/openstack-refstack-bionic-queens/README.md
- development/openstack-refstack-bionic-queens/bundle.yaml
- stable/ceph-base/bundle.yaml
- stable/openstack-base/bundle.yaml
- stable/openstack-lxd/bundle.yaml
- stable/openstack-telemetry/bundle.yaml
Update Stable Bundles
Create bionic-queens refstack bundle
> 18.05 Bundles

- development/shared/openrc
- stable/shared/openrc
Sync changes landed in openstack-charmers/openstack-charm-testing#19
> Sync o-c-t tools

- development/openstack-lxd-bionic-queens/README.md
- development/openstack-lxd-bionic-queens/openrcv3_domain
- development/openstack-lxd-bionic-queens/openrcv3_project
- development/openstack-lxd-bionic-rocky/README.md
- development/openstack-lxd-bionic-rocky/bundle.yaml
- development/openstack-lxd-bionic-rocky/neutron-ext-net-ksv3
- development/openstack-lxd-bionic-rocky/neutron-tenant-net-ksv3
- development/openstack-lxd-bionic-rocky/openrc
- development/openstack-lxd-bionic-rocky/openrcv3_domain
- development/openstack-lxd-bionic-rocky/openrcv3_project
- development/openstack-lxd-xenial-mitaka/bundle.yaml
Updates to add bionic-rocky for lxd and also some modifications to cope with regressions on bionic-queens and xenial-mitaka.
> Bionic rocky cycle updates

- development/openstack-base-bionic-stein/README.md
- development/openstack-base-bionic-stein/bundle.yaml
- development/openstack-base-bionic-stein/openstack-base-spaces-overlay.yaml
- stable/openstack-base/README.md
- stable/openstack-base/bundle.yaml
- stable/openstack-base/openstack-base-spaces-overlay.yaml
- stable/openstack-telemetry/bundle.yaml
- stable/openstack-telemetry/openstack-telemetry-spaces-overlay.yaml
- stable/overlays/openstack-base-spaces-overlay.yaml
- stable/overlays/openstack-telemetry-spaces-overlay.yaml
Move network space declarations into overlay examples
> Move network space declarations into overlay examples

- development/ceph-base-disco-mimic/bundle.yaml
> remove ntp

- stable/overlays/loadbalancer-octavia.yaml
Use stein and add gss + ``octavia-diskimage-retrofit``
> Update loadbalancer overlay

- stable/openstack-base/README.md
As seen on the Juju forum:
https://discourse.jujucharms.com/t/openstack-base-version/2435
**Please also publish the bundle so the Store gets updated.**
> Update README from Stein to Train

- development/openstack-base-eoan-train-mysql8-ovn/README.md
- development/openstack-base-eoan-train-mysql8-ovn/bundle.yaml
- development/openstack-base-eoan-train-mysql8-ovn/file-assertions.yaml
- development/openstack-base-eoan-train-mysql8-ovn/neutron-ext-net-ksv3
- development/openstack-base-eoan-train-mysql8-ovn/neutron-tenant-net-ksv3
- development/openstack-base-eoan-train-mysql8-ovn/openrc
- development/openstack-base-eoan-train-mysql8-ovn/openrcv3_domain
- development/openstack-base-eoan-train-mysql8-ovn/openrcv3_project
- development/openstack-base-eoan-train-mysql8-ovn/openstack-base-spaces-overlay.yaml
- development/openstack-base-eoan-train-mysql8-ovn/test-requirements.txt
- development/openstack-base-eoan-train-mysql8-ovn/tests/bundles/bundle.yaml
- development/openstack-base-eoan-train-mysql8-ovn/tests/bundles/overlays/local-charm-overlay.yaml.j2
- development/openstack-base-eoan-train-mysql8-ovn/tests/tests.yaml
- development/openstack-base-eoan-train-mysql8-ovn/tox.ini
For zaza testing MySQL8 and OVN.
> Eoan Train MySQL8 and OVN Bundle

- development/openstack-base-eoan-train-mysql8-migration/README.md
- development/openstack-base-eoan-train-mysql8-migration/bundle.yaml
- development/openstack-base-eoan-train-mysql8-migration/file-assertions.yaml
- development/openstack-base-eoan-train-mysql8-migration/neutron-ext-net-ksv3
- development/openstack-base-eoan-train-mysql8-migration/neutron-tenant-net-ksv3
- development/openstack-base-eoan-train-mysql8-migration/openrc
- development/openstack-base-eoan-train-mysql8-migration/openrcv3_domain
- development/openstack-base-eoan-train-mysql8-migration/openrcv3_project
- development/openstack-base-eoan-train-mysql8-migration/openstack-base-spaces-overlay.yaml
- development/openstack-base-eoan-train-mysql8-migration/test-requirements.txt
- development/openstack-base-eoan-train-mysql8-migration/tests/bundles/bundle.yaml
- development/openstack-base-eoan-train-mysql8-migration/tests/bundles/overlays/local-charm-overlay.yaml.j2
- development/openstack-base-eoan-train-mysql8-migration/tests/tests.yaml
- development/openstack-base-eoan-train-mysql8-migration/tox.ini
Migration tests from percona to mysql8.
Dependent on:
https://github.com/openstack-charmers/zaza-openstack-tests/pull/180
> Percona Cluster to Mysql InnoDB Cluster migration

- development/shared/neutron-ext-net-ksv3
- development/shared/neutron-tenant-net-ksv3
Depends on https://github.com/openstack-charmers/openstack-charm-testing/pull/60
> Add arg for selecting physical network

- development/openstack-base-focal-ussuri-ovn/bundle.yaml
last weekend we added a new osd to this bundle to try to work around an error - it didnt work, so i am reverting it.
> revert last commit

- development/openstack-base-focal-ussuri-ovn/README.md
- development/openstack-base-focal-ussuri-ovn/bundle.yaml
- development/openstack-telemetry-focal-ussuri-ovn/bundle.yaml
- stable/openstack-base/README.md
- stable/openstack-base/bundle.yaml
- stable/openstack-telemetry/bundle.yaml
In reference to release note [0] and the tracking bugs [1][2].
0: https://docs.openstack.org/charm-guide/latest/2005.html#openstack-ussuri-packages-for-ubuntu-20-04-lts
1: https://bugs.launchpad.net/bugs/1877642
2: https://bugs.launchpad.net/bugs/1863021
> Drop proposed on Focal now that Ussuri SRU is complete

- development/openstack-base-focal-ussuri-ovn/bundle.yaml
- development/shared/openrcv2
- development/shared/openrcv3_domain
- development/shared/openrcv3_project
- stable/openstack-base/bundle.yaml
- stable/shared/openrcv2
- stable/shared/openrcv3_domain
- stable/shared/openrcv3_project
Bump stable version for ceph-radosgw to include version which
includes fixes for handling of certificates relation.
> Add missing certificates relation for ceph-radosgw

- development/openstack-base-focal-wallaby/README.md
- development/openstack-base-focal-wallaby/bundle.yaml
* Improve comments at the top of the bundle
* Add explicit relation endpoints for two relations
* Remove the first line of the bundle `---`. This seems to be a delimiter for an overlay?
* Remove redundant series specification in the `machines` section
* Fix up final wording of the README
> Improve openstack-base

- development/openstack-converged-networking-focal-ussuri/README.md
- development/openstack-converged-networking-focal-ussuri/bundle.yaml
- development/openstack-converged-networking-focal-ussuri/file-assertions.yaml
- development/openstack-converged-networking-focal-ussuri/openrc
- development/openstack-converged-networking-focal-ussuri/openrcv3_domain
- development/openstack-converged-networking-focal-ussuri/openrcv3_project
- development/openstack-converged-networking-focal-ussuri/openstack-base-spaces-overlay.yaml
- development/openstack-converged-networking-focal-ussuri/openstack-converged-networking-spaces-overlay.yaml
- development/openstack-converged-networking-focal-ussuri/test-requirements.txt
- development/openstack-converged-networking-focal-ussuri/tests/bundles/bundle.yaml
- development/openstack-converged-networking-focal-ussuri/tests/bundles/overlays/local-charm-overlay.yaml.j2
- development/openstack-converged-networking-focal-ussuri/tests/tests.yaml
- development/openstack-converged-networking-focal-ussuri/tox.ini
Note only two changes are necessary from openstack base bundle:
* Set data-port to what is configured in MAAS for the sueprbond
* Set space names to match
> Converged Networking Bundle

- development/openstack-base-hirsute-wallaby/README.md
- development/openstack-base-hirsute-wallaby/bundle.yaml
- development/openstack-base-hirsute-wallaby/openrc
- development/openstack-base-hirsute-wallaby/openrcv3_domain
- development/openstack-base-hirsute-wallaby/openrcv3_project
- development/openstack-base-hirsute-wallaby/openstack-base-spaces-overlay.yaml
- development/openstack-base-hirsute-wallaby/test-requirements.txt
- development/openstack-base-hirsute-wallaby/tests/bundles/bundle.yaml
- development/openstack-base-hirsute-wallaby/tests/bundles/overlays/local-charm-overlay.yaml.j2
- development/openstack-base-hirsute-wallaby/tests/tests.yaml
- development/openstack-base-hirsute-wallaby/tox.ini
Nearly identical to openstack-base-focal-wallaby.
> Add openstack-base-hirsute-wallaby bundle

- development/openstack-base-focal-xena/README.md
- development/openstack-base-focal-xena/bundle.yaml
- development/openstack-base-focal-xena/openrc
- development/openstack-base-focal-xena/openrcv3_domain
- development/openstack-base-focal-xena/openrcv3_project
- development/openstack-base-focal-xena/openstack-base-spaces-overlay.yaml
- development/openstack-base-focal-xena/test-requirements.txt
- development/openstack-base-focal-xena/tests/bundles/bundle.yaml
- development/openstack-base-focal-xena/tests/bundles/overlays/local-charm-overlay.yaml.j2
- development/openstack-base-focal-xena/tests/tests.yaml
- development/openstack-base-focal-xena/tox.ini
- development/openstack-base-impish-xena/README.md
- development/openstack-base-impish-xena/bundle.yaml
- development/openstack-base-impish-xena/openrc
- development/openstack-base-impish-xena/openrcv3_domain
- development/openstack-base-impish-xena/openrcv3_project
- development/openstack-base-impish-xena/openstack-base-spaces-overlay.yaml
- development/openstack-base-impish-xena/test-requirements.txt
- development/openstack-base-impish-xena/tests/bundles/bundle.yaml
- development/openstack-base-impish-xena/tests/bundles/overlays/local-charm-overlay.yaml.j2
- development/openstack-base-impish-xena/tests/tests.yaml
- development/openstack-base-impish-xena/tox.ini
- development/openstack-telemetry-focal-xena/README.md
- development/openstack-telemetry-focal-xena/bundle.yaml
- development/openstack-telemetry-focal-xena/openrc
- development/openstack-telemetry-focal-xena/openrcv3_domain
- development/openstack-telemetry-focal-xena/openrcv3_project
- stable/ceph-base/bundle.yaml
- stable/openstack-telemetry/bundle.yaml
1. Update the stable bundles
2. Add new Xena development bundles
> Updates post-21.04-release

- development/openstack-telemetry-focal-ussuri-ovn/bundle.yaml
- development/openstack-telemetry-focal-ussuri-ovn/test-requirements.txt
- development/openstack-telemetry-focal-ussuri-ovn/tests/bundles/bundle.yaml
- development/openstack-telemetry-focal-ussuri-ovn/tests/bundles/overlays/bundle.yaml.j2
- development/openstack-telemetry-focal-ussuri-ovn/tests/tests.yaml
- development/openstack-telemetry-focal-ussuri-ovn/tox.ini
- development/openstack-telemetry-focal-victoria/bundle.yaml
- development/openstack-telemetry-focal-victoria/test-requirements.txt
- development/openstack-telemetry-focal-victoria/tests/bundles/bundle.yaml
- development/openstack-telemetry-focal-victoria/tests/bundles/overlays/bundle.yaml.j2
- development/openstack-telemetry-focal-victoria/tests/tests.yaml
- development/openstack-telemetry-focal-victoria/tox.ini
- development/openstack-telemetry-focal-wallaby/bundle.yaml
- development/openstack-telemetry-focal-wallaby/test-requirements.txt
- development/openstack-telemetry-focal-wallaby/tests/bundles/bundle.yaml
- development/openstack-telemetry-focal-wallaby/tests/bundles/overlays/bundle.yaml.j2
- development/openstack-telemetry-focal-wallaby/tests/tests.yaml
- development/openstack-telemetry-focal-wallaby/tox.ini
- development/openstack-telemetry-focal-xena/bundle.yaml
- development/openstack-telemetry-focal-xena/test-requirements.txt
- development/openstack-telemetry-focal-xena/tests/bundles/bundle.yaml
- development/openstack-telemetry-focal-xena/tests/bundles/overlays/bundle.yaml.j2
- development/openstack-telemetry-focal-xena/tests/tests.yaml
- development/openstack-telemetry-focal-xena/tox.ini
- development/openstack-telemetry-groovy-victoria/bundle.yaml
- development/openstack-telemetry-groovy-victoria/test-requirements.txt
- development/openstack-telemetry-groovy-victoria/tests/bundles/bundle.yaml
- development/openstack-telemetry-groovy-victoria/tests/bundles/overlays/bundle.yaml.j2
- development/openstack-telemetry-groovy-victoria/tests/tests.yaml
- development/openstack-telemetry-groovy-victoria/tox.ini
And add Zaza boilerplate.
Validated focal-victoria against our arm64 lab.
> Add missing ceilometer-vault relation

- stable/openstack-telemetry/openrc
> Fix stable openstack-telemetry openrc symlink

- development/openstack-base-focal-yoga/README.md
A few improvements and a fix for how it renders in HTML in the charm store.
> Improve openstack-base bundle README
